- name: APP Copy Certificate to /etc/ssl/
  copy: src=./{{ site_url }}.crt dest=/etc/ssl/{{ site_url }}.crt owner=root group=root mode="u=r,g=,o="
  notify: NGINX Restart Nginx Service

- name: APP Copy Private key to /etc/ssl/
  copy: src=./{{ site_url }}.pem dest=/etc/ssl/{{ site_url }}.pem   owner=root group=root mode="u=r,g=,o="
  notify: NGINX Restart Nginx Service

- name: APP Copy server conf file to sites-enabled
  template: src={{ site_url }}.j2 dest=/etc/nginx/sites-enabled/{{ site_url }} owner=root group=root mode="u=rw,g=,o="
  notify: NGINX Restart Nginx Service
